package com.ivankoi;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2015-08-01T22:18:52.832+02:00
 * Generated source version: 2.4.6
 * 
 */
@WebService(targetNamespace = "http://www.ivankoi.com/", name = "CalculatorPojoWsRpc")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface CalculatorPojoWsRpc {

    @WebResult(name = "result", targetNamespace = "http://www.ivankoi.com/", partName = "result")
    @WebMethod
    public double calculatePower(
        @WebParam(partName = "base", name = "base")
        double base,
        @WebParam(partName = "exponent", name = "exponent")
        double exponent
    );
}
