<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="Calculator_pojo_ws_rpc"
	targetNamespace="http://www.ivankoi.com/" xmlns:ns1="http://schemas.xmlsoap.org/soap/http"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.ivankoi.com/"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<wsdl:message name="calculatePowerResponse">
		<wsdl:part name="result" type="xsd:double">
		</wsdl:part>
	</wsdl:message>
	<wsdl:message name="calculatePower">
		<wsdl:part name="base" type="xsd:double">
		</wsdl:part>
		<wsdl:part name="exponent" type="xsd:double">
		</wsdl:part>
	</wsdl:message>
	<wsdl:portType name="CalculatorPojoWsRpc">
		<wsdl:operation name="calculatePower">
			<wsdl:input message="tns:calculatePower" name="calculatePower">
			</wsdl:input>
			<wsdl:output message="tns:calculatePowerResponse" name="calculatePowerResponse">
			</wsdl:output>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="Calculator_pojo_ws_rpcSoapBinding"
		type="tns:CalculatorPojoWsRpc">
		<soap:binding style="rpc"
			transport="http://schemas.xmlsoap.org/soap/http" />
		<wsdl:operation name="calculatePower">
			<soap:operation soapAction="" style="rpc" />
			<wsdl:input name="calculatePower">
				<soap:body namespace="http://www.ivankoi.com/" use="literal" />
			</wsdl:input>
			<wsdl:output name="calculatePowerResponse">
				<soap:body namespace="http://www.ivankoi.com/" use="literal" />
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="Calculator_pojo_ws_rpc">
		<wsdl:port binding="tns:Calculator_pojo_ws_rpcSoapBinding"
			name="CalculatorPojoWsRpcPort">
			<soap:address location="http://localhost:8080/as7.ws/CalculatorPojoWsRpc" />
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>