
package com.ivankoi;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "StoreManagerWebService", targetNamespace = "http://www.ivankoi.com", wsdlLocation = "http://localhost:8080/AppStoreWeb/storeManagerWebService?wsdl")
public class StoreManagerWebService
    extends Service
{

    private final static URL STOREMANAGERWEBSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.ivankoi.StoreManagerWebService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.ivankoi.StoreManagerWebService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/AppStoreWeb/storeManagerWebService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/AppStoreWeb/storeManagerWebService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        STOREMANAGERWEBSERVICE_WSDL_LOCATION = url;
    }

    public StoreManagerWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StoreManagerWebService() {
        super(STOREMANAGERWEBSERVICE_WSDL_LOCATION, new QName("http://www.ivankoi.com", "StoreManagerWebService"));
    }

    /**
     * 
     * @return
     *     returns StoreManagerWebEndpoint
     */
    @WebEndpoint(name = "StoreManagerWebEndpointPort")
    public StoreManagerWebEndpoint getStoreManagerWebEndpointPort() {
        return super.getPort(new QName("http://www.ivankoi.com", "StoreManagerWebEndpointPort"), StoreManagerWebEndpoint.class);
    }

}
